library(dplyr)
raw <- read.csv("../data/SraRunTable.txt")
dochna <- raw %>% filter(Cultivar == "dochna")
della <- raw %>% filter(Cultivar == "Della") 
keller <- raw %>% filter(Cultivar == "Keller") 
RTx430 <- raw %>% filter(Cultivar == "RTx430") 
BTx642 <- raw %>% filter(Cultivar == "BTx642") 


RTx642_filtered <- RTx430[sample(nrow(RTx430), size=20), ]
RTx430_filtered <- RTx430[sample(nrow(RTx430), size=20), ]
BTx642_filtered <- BTx642[sample(nrow(BTx642), size=20), ]

accessions_BTx642 <- BTx642_filtered %>%  select(Run)

write.table(accessions_BTx642, "accessions_BTx642.txt", row.names = F, col.names = F, quote = F)
write.table(accessions_RTx430, "accessions_RTx430.txt", row.names = F, col.names = F, quote = F)

study_1_della <- della %>% filter(BioProject == "PRJNA842061")
study_1_rio <- rio %>% filter(SRA.Study == "SRP120385")
accessions_della1 <- study_1_della %>%  select(Run)
accessions_rio1 <- study_1_rio %>% select(Run)
write.table(accessions_rio1, "rio_accessions.txt", row.names = F, col.names = F, quote = F)
write.table(accessions_della1, "della_accessions.txt", row.names = F, col.names = F, quote = F)


accessions_keller <- head(keller, 20) %>% select(Run)
write.table(accessions_keller, "keller_accessions.txt", row.names = F, col.names = F, quote = F)

### Cane

library(dplyr)
library(tidyr)
library(stringr)
# cane annotation table for conekt
# create aux vector with biosample and run_accession
# downloaded from ENA bioproject webpage

###### PERLO 2022 10.1007/s00122-022-04058-3 #############
aux <- read.table("/home/jm/Downloads/filereport_read_run_PRJEB44480_tsv.txt", header = T)
# load ENA table generated by:
# curl -X GET "https://www.ebi.ac.uk/ena/portal/api/search?result=sample&query=study_accession=PRJEB44480&fields=sample_description&format=tsv" -o biosamples.tsv
ENA_table <- read.table("biosamples.tsv", header = T, sep = "\t")
# load renatos's table
renato <- read.table("/home/jm/Downloads/Scp1_expression_annotation.txt", header = T, sep = "\t")
# separate from ENA table sample_description
separated_wider <- separate_wider_delim(ENA_table, cols = sample_description, delim = " - ", names = c("cultivar", "tissue", "time", "genotype", "internode", "rep"))
# merge ENA separated table with aux vector to map run accession to biosample
df1 <- merge(x = aux, y = separated_wider, by = "sample_accession")
# changue column name to match renato's table
names(df1)[names(df1) == 'run_accession'] <- 'SampleID'
# merge df1 with renato's table
df2 <- merge(x = df1, y = renato, by = "SampleID")
# select columns of interest
filtered <- df2[c("SampleID", "tissue", "time", "genotype", "internode", "DOI", "Strandness", "Layout", "PO_anatomy", "PO_dev_stage", "PECO")]
# make a second aux vector to save the ConditionDescription column that will be used in final table
aux2 <- filtered %>% select(time, genotype, internode) %>% unite(col = ConditionDescription)
# add ConditionDescription table to final table
filtered$ConditionDescription <- aux2$ConditionDescription
filtered$Replicate <- 3
perlo <- filtered[c(-2, -3 , -5)]
############# HOANG 2017 ######
# read SRA table from NCBI
SRA_table <- read.table("/home/jm/Downloads/SraRunTable.csv", sep = ",",  header = T)
# relate run and library name wich have the genotype and other information
aux <- SRA_table %>% select(Run, Library.Name)
# discard SUGIT transcriptome reference accessesions
aux <- aux[1:80,]
# separate Library.name information in several columns
separated_wider <- separate_wider_delim(aux, cols = Library.Name, delim = "_", names = c("Position", "tissue", "trash", "genotypeCODE", "genotype", "sample"))
# take only run and  genotype
df1 <- separated_wider[c("Run", "genotype")]
# changue column name to match renato's table
names(df1)[names(df1) == 'Run'] <- 'SampleID'
# merge df1 with renato's table
df2 <- merge(x = df1, y = renato, by = "SampleID")
df2$ConditionDescription <- paste0(df2$genotype, "_", df2$ConditionDescription)
df2$Replicate <- 2
hoang <- df2
##### Correr 10.1186/s12864-020-07091-y ############
renato <- read.table("/home/jm/Downloads/Scp1_expression_annotation.txt", header = T, sep = "\t")
raw <- renato[grep("10.1186/s12864-020-07091-y", x = renato$DOI),]
raw$genotype <- raw$ConditionDescription
correr <- raw
## merger correr, perlo and hoang
all <- rbind(perlo, hoang, correr)
target_genotypes <- c("KQB09-20432", "SRA5", "SRA3", "Q238", "Q157", "Q151", "Q135")
all_filtered <- all %>% filter(genotype %in% target_genotypes)
for_snakemake <- all_filtered %>% select(genotype, SampleID) order()
write.table(for_snakemake, "sugarcane_accessions.txt", sep = "\t", row.names = F, col.names = T, quote = F)
